package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "fcopy-server",
    srcs = [
        "fcopy_server.cpp",
        "file_manager.cpp",
        "file_manager.h",
        "load_config.cpp",
        "service.cpp",
        "service.h",
    ],
    deps = [
        "//src/common:common"
    ],
)
