package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "fcopy-cli",
    srcs = [
        "file_sender.cpp",
        "fcopy_cli.cpp",
        "file_sender.h",
    ],
    deps = [
        "//src/common:common"
    ],
)
